[CAZB-4679] - Username enumeration fix
InformedSolutions/JAQU-CAZ-MOD-UI pull request #369
Opened 2021-05-24 14:29 UTC by proctorj

## Motivation and Context

## Description

## How Has This Been Tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] It contains only changes required by issue (does not contain other PR)
- [ ] Includes a link to an issue (if apply)
- [ ] I have added tests to cover my changes.

2021-05-24 14:44 UTC, likeuwill requested changes

2021-05-24 14:44 UTC, likeuwill commented on Gemfile.lock
> +   ruby 3.0.1p64
please check here how to update ruby, u should update more files
https://github.com/InformedSolutions/JAQU-CAZ-Ruby-Template/commit/4ec77ad9f0c30c5a8478256a5303f57f1ef45fb4

2021-05-25 08:57 UTC, proctorj commented on Gemfile.lock
> +   ruby 3.0.1p64
Hey @likeuwill, were the changes needed not made here? - https://github.com/InformedSolutions/JAQU-CAZ-MOD-UI/commit/b84ce7e7c4011b7da3924dcc1730958d382105c5

2021-05-25 09:57 UTC, likeuwill commented on Gemfile.lock
> +   ruby 3.0.1p64
Correct, I thought u updating ruby, but it was already.

2021-05-25 09:57 UTC, likeuwill approved these changes

2021-05-25 09:57 UTC, merged